//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornek1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciBilgileri
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public string adSoyad { get; set; }
        public string gsmNo { get; set; }
        public Nullable<bool> aktifMi { get; set; }
    }
}
